{% set name = "Orange3-ImageAnalytics" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/orange3_imageanalytics-{{ version }}.tar.gz
  sha256: 4bbc65202dc6f3c83969319f62f5153ae7e05b3fd69db18caf869cdf8bb7859f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - trubar >=0.3.3
  run:
    - python >={{ python_min }}
    - anyqt
    - ndf >=0.1.4
    - numpy >=1.16
    - orange-canvas-core >=0.2.2
    - orange-widget-base >=4.23.0
    - orange3 >=3.35.0
    - pillow >=6.2.0
    - requests
    - requests-cache
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - orangecontrib.imageanalytics

about:
  home: https://github.com/biolab/orange3-imageanalytics
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Orange3 add-on for dealing with image related tasks

  description: |
    Orange3 Image Analytics is an add-on for the Orange3 data mining suite.
    It provides extensions for importing/creating labeled image data sets and
    embedding them through a variety of pre-trained deep neural networks.
  doc_url: http://orange3-imageanalytics.readthedocs.io
  dev_url: https://github.com/biolab/orange3-imageanalytics

extra:
  recipe-maintainers:
    - primozgodec
    - vesnaT
    - markotoplak
