{% set name = "Orange3-ImageAnalytics" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 104daed88854521a861f1491eeecd169c0502befcb0d1a78783f29d3ff1ddf38
  # path: ./orange3-imageanalytics

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - scipy
    - numpy >=1.16.*
    - orange3 >=3.25.0
    - pillow >=6.2.0
    - requests
    - cachecontrol
    - lockfile
    - ndf >=0.1.4

test:
  imports:
    - orangecontrib.imageanalytics
  requires:
    - pytest
  commands:
    # qt fails - display not found
    # - export QT_QPA_PLATFORM=offscreen  # [not win]
    - XVFBARGS="-screen 0 1280x1024x24"
    - DISPLAY=localhost:1.0 xvfb-run -a -s "$XVFBARGS" pytest --pyargs orangecontrib.imageanalytics -v

about:
  home: https://github.com/biolab/orange3-imageanalytics
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Orange3 add-on for dealing with image related tasks

  description: |
    Orange3 Image Analytics is an add-on for the Orange3 data mining suite.
    It provides extensions for importing/creating labeled image data sets and
    embedding them through a variety of pre-trained deep neural networks.
  doc_url: http://orange3-imageanalytics.readthedocs.io
  dev_url: https://github.com/biolab/orange3-imageanalytics

extra:
  recipe-maintainers:
    - primozgodec
    - astaric
